name: "Check flake"
on:
  pull_request:
jobs:
  check-flake:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v25
      - run: nix flake check
